format_version: '10'
common:
  serviceBuild: &serviceBuild
    - build:
        clean_workspace: true
        environment_variables:
          SKIP_ECR_PUSH: "true"
          SONAR_USER_HOME: "/tmp"
        jobs:
          Build:
            elastic_profile_id: gocd-agent-dind-2023
            artifacts:
              - build:
                  source: cruise-output/buildReport*.json
              - build:
                  source: devBranchRevision.json
            tasks:
              - script: |
                  c12e-common.sh dev
                  sonar-scan.sh scan
pipelines:
  scuttle:
    group: fabric6
    materials:
      scuttle:
        git: git@github.com:CognitiveScale/scuttle.git
        branch: main
    stages: *serviceBuild
  scuttle-pr:
    group: pull-requests
    materials:
      scuttle:
        plugin_configuration:
          id: github.pr
          version: 1
        options:
          url: git@github.com:CognitiveScale/scuttle.git
          defaultBranch: main
    stages: *serviceBuild
